services:
  mysql:
    image: mysql:8.0
    container_name: nexustasks_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nexustasks_dev
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nexus_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: nexustasks_mailpit
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI : http://localhost:8025
    networks:
      - nexus_network

volumes:
  mysql_data:

networks:
  nexus_network:
    driver: bridge