services:
  mysql:
    image: mysql:8.0
    container_name: nexustasks_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nexustasks_dev
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nexus_network

volumes:
  mysql_data:

networks:
  nexus_network:
    driver: bridge