spring:
  datasource:
    url: jdbc:mysql://localhost:3307/nexustasks_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate # On utilisera Flyway plus tard, donc on désactive la génération auto
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    com.nexustasks: DEBUG
    org.springframework.security: DEBUG