spring:
  application:
    name: NexusTasks
  profiles:
    active: dev # Profil par défaut si aucun n'est spécifié

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F428472B4B62503545357565B5258} # 512-bit key for HS512 (Dev default, MUST override in Prod)
  access-token-expiration: 900000 # 15 minutes
  refresh-token-expiration: 604800000 # 7 days

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never # Sécurité : ne jamais exposer les stack traces
    include-path: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always